### ISSUE TITLE
After deleting like.. 1000+ messages (3 months worth) it no longer deletes stuff

### ISSUE THREAD

**Issue by whoc7426** [theahura/shoot-the-messenger#10]
I guess it's a limitation of the API or something, but it's buggy a little bit. It still did a wonderful job and I appreciate it a lot. Thank you for making this script, it's wonderful. I will keep using it.

**Comment by theahura** [comment]
O that's really interesting. Do you think you could send me some kind of screen cap or something (especially of the console log)? I've successfully used this to delete 3 years worth of messages.

**Comment by pizzatron** [comment]
Yeah I've got this exact same issue.

**Comment by theahura** [comment]
Thanks for commenting! 

Some things that would help with debugging. Can you send a dump of the console (hit f12 to open developers tools, and then go to the console tab).

**Comment by vemfanvet** [comment]
I'm also having issues with being rate limited. Will post console error message below
Would be great if you could implement a feature that waits 5 minutes when the error appears. 

`main.js:479 Checking existing removal process.
juzP_cJCVbb.js?_nc_x=cWPZmTrOynF:54 ErrorUtils caught an error:

Write error response from server

Subsequent non-fatal errors won't be logged; see https://fburl.com/debugjs.
errorListener @ juzP_cJCVbb.js?_nc_x=cWPZmTrOynF:54
`

**Comment by theahura** [comment]
Yea this is a known problem, and at least before it wasn't actually throwing an error but was just failing silently. Maybe it is now which will make it easier to work around?

Afaict previous iterations would just remove the rate limit after 5-10 minutes from the first refusal, which meant you could just keep repeating requests until they started working again. Is that no longer the case?

**Comment by vemfanvet** [comment]
I've done a bit of testing but I have never worked with javascript before so i'm not really sure what I'm doing.

First of all I had issues with the scrolling function. It would scroll up, select some messages and then keep scrolling up 4-5 times. After this it got stuck in a loop "waiting for messages to populate" even though there were loads of messages loaded at the bottom of the chat. 

To fix this i removed line 193 through 221.
Ideally i'd want to put in a pause or a counter of some sort so that it doesn't scroll up more than once before trying to delete any messages. Since I don't know javascript i just removed the entire section and it seemed to work.
This did however introduce a new issue due to some static messages covering the entire screen, thus it cannot load as many messages since it never scrolls up. 
The static messages i'm referring to is when someone changes the "thumbs up" to another emoji or when you change the theme/color of the chat. These messages can take up the entire screen so the scrolling function is necessary for some chats.


Next issue was the rate limiting.
To "fix" this I increased the sleep timer on line 227 and 229 to 20000 on both.
It has been stable for over an hour now as long as I don't change my tab, lock the computer or screensaver goes on.

**Comment by vemfanvet** [comment]
> Yea this is a known problem, and at least before it wasn't actually throwing an error but was just failing silently. Maybe it is now which will make it easier to work around?
> 
> Afaict previous iterations would just remove the rate limit after 5-10 minutes from the first refusal, which meant you could just keep repeating requests until they started working again. Is that no longer the case?

When the script got stuck due to rate limiting I found out that if I paused it for just 30-60 seconds I could start unsending messages again. But if I left it running for several minutes while stuck it wouldn't let me manually unsend anything

**Comment by vemfanvet** [comment]
The 20000ms sleep timer i added works great on a laptop screen but does not work on a 1440p 27" monitor, so it's not really a viable fix. 

From what I can tell the error message seems to be consistent whenever you get rate limited, but sometimes the message will remain in console even though I'm not limited anymore so I'm not to sure about it. Might work to add a 60-120 sec pause and then refresh page whenever this error pops up

**Comment by theahura** [comment]
> To fix this i removed line 193 through 221.

Interesting. Those lines are necessary for actually scrolling up, as you noticed. But I guess if you're just deleting messages as you go, maybe scrolling isn't necessary. This was in part a speed thing, like being able to remove more messages in one go, but if it's causing problems I'm ok with removing that code. I'll dig into it, or would appreciate if you submitted a PR. 

> To "fix" this I increased the sleep timer on line 227 and 229 to 20000 on both.

Note that this will definitely make things much slower, especially if you have thousands of messages. YMMV.

> Might work to add a 60-120 sec pause and then refresh page whenever this error pops up

Agreed, before there just wasn't an error message. I'll do some digging to see what the nature of that error is and whether it can be captured.

**Comment by vemfanvet** [comment]
I've done a lot of testing now and I cannot get it to run 100% unattended.

I did however get it stable enough to not get rate limited by increasing the sleep timers at different parts of the code.

The major issue is that it cannot remove any links/thumbs/stickers even though I'm able to unsend them manually.
If I leave the script running for some hours the chat will be filled with links and thumbs that I can manually unsend with no issue, but the script doesn't for some reason.

A workaround for this would be to use the scrolling feature, but since I couldn't get that to work I am unable to run the script unattended.

So it either has to be able to remove links/thumbs/stickers or the scrolling feature has to work without getting stuck in a loop "waiting for messages to populate".

**Comment by theahura** [comment]
There are a few lines of code in the extension that should get rid of links/stickers. I wonder if those selectors aren't working anymore, maybe facebook changed them? 

See: https://github.com/theahura/shoot-the-messenger/blob/main/main.js#L99

**Comment by vemfanvet** [comment]
> There are a few lines of code in the extension that should get rid of links/stickers. I wonder if those selectors aren't working anymore, maybe facebook changed them?

The links/thumbs/stickers gets hidden as you mention, but the timestamps does not. Since I deleted the scrolling part the chat gets filled with timestamps and no other messages are able to load.

Not sure how easy it would be, but if possible the script could hide the timestamps at the same time as it hides the links?
Either that or the scroller has to function

Timetamps
Image: https://i.imgur.com/9YHYwM4.png
Code: https://i.imgur.com/EIwyYnY.png


When deleting the row `<div role="row">` the entire timestamp gets removed.

Had the same issue with all chats where the emoji and theme were frequently changed.
Image: https://i.imgur.com/xRQA9AD.png
Code: https://i.imgur.com/YSHHnhU.png

Seems like timestamps/themes/emojis all use the `role="gridcell"`, `data-scope="message_table"` and `class="lzcic4wl"`

I hope this information helps

**Comment by vemfanvet** [comment]
I removed line 99 through 113 and line 117. Now it successfully removes links, thumbs and stickers! 

However, in some chats I am unable to remove any links, even manually, and it's not related to rate limiting. 
I have some chats with 20+ links that I haven't been able to remove for the past week. The script will fail on these chats so this solution is not 100% stable.

Best would be if it tried to remove all, and if some messages failed after x amount of tries it would mark them as bad element and hide it.

**Comment by theahura** [comment]
Wait so you're saying it _is_ able to remove links/stickers/thumbsup instead of just hiding them? that's very interesting. For a while that was a terminal issue, I wonder if fb fixed that on the backend for newer messenger chains. I suspect older ones will still have issues though

**Comment by theahura** [comment]
I added a bunch of changes that should fix issues with blocking on scroll, as well as hiding 'bad' or 'unremovable' dom elements like stickers, thumbs, links, status messages, and timestamps. I'm going to close this out but reopen this if there are still issues.
