### ISSUE TITLE
Doesn seem to be working anymore, no response to messenger window at all

### ISSUE THREAD

**Issue by TylerDurden1983** [theahura/shoot-the-messenger#108]
Installed both the extension from the chrome store, and manually w/ dev mode from github download, no response from the extension :(

**Comment by theahura** [comment]
looks like it still works on my end -- do you have logs or screenshots? what do you mean by 'no response'?

**Comment by gaveitatry2** [comment]
Don't waste your time with this garbage app. It might delete the first dozen or so messages, but try deleting a month or two of messages and it won't work. In September, I was able to delete back as far as March 31. But then I could keep this extension running all day and it wouldn't ever delete further back than that.

Some guy named 8SecSleepy will tell you "you can disable the reloading functionality" and "disable the refresh for the conversation you had trouble with." So like maybe that is a workaround to get a broken extension to work. But there is no option in the extension to disable reloading or refreshing. That option is nowhere to be found anywhere in the extension. And a search on Google doesn't show any way to disable refreshing in Chrome. So I don't know what he is talking about.

This theahura developer just talks out his behind and makes empty promises. He wrote on Sep 10 that "Maybe we could improve this by having a toggle in the extension that disables the entire refresh loop". Well it is now almost Dec 10, three months later. Do you see that option in the extension? No. Just like he wrote three months ago on Sep 24 "Add a mode to delete all messages". Did he add that mode within the last three months? No. He will keep taking your free coffee donations, but he won't fix a broken app or put any information on his extension page about it being broken. A decent human being would write on their extension "My extension is broken as f and will only delete a couple dozen messages at most." I wasted 72 hours on this crap extension and in the end, didn't have many messages deleted at all, and it would have been faster to delete the messages manually myself. 72 hours is a long time. No one wants to go through that, and I wouldn't have had to if there had be more honesty and transparency.

I've submitted a few suggestions, all of which he approved of and said he would put on his roadmap. It's been a few months. Not a single one has been implemented. I'm not a fan of deleting ALL messages because as the other guy said, it would be a lot slower. But which is better? Having the extension take a really long time to delete extra messages but in the end you get all the messages deleted? Or having the extension take forever to scroll up, refresh, and repeat without actually deleting anything?

Oh, and that 8SecSleeper guy will say "furthermore, you can use the open source python library to unsend messages without any of the issues or limitations a chrome extension has." Well, hell. Does he think we all know how to use python? I don't even know how to download a python library let alone use it. The extension DOES NOT WORK. There are dozens of issues on this very GitHub that were created saying as much. If the extension DOES NOT WORK, then maybe these workarounds should be published on the front GitHub page. Step by step instructions on how to accomplish what we want without the extension (since it is broken). How many seconds would it take to explain how to "disable the reloading functionality" on the GitHub page for those of us who want to see if the extension will work if refreshing is disabled.

Here is something laughable. This 8SecSleeper guy goes on and on about how easy it is to code and it only takes a few seconds. "You can only do so much in a chrome extension. Deleting the unsent part will simply make it take forever. You can code that part quite easily if so desired." Well if it is so easy to add tiny features like that to the code, then why the hell hasn't the theahru developer added any of those so-called roadmap features in the last three months? If he doesn't have the time to "easily add" things to his code and his extension is broken, why not just take the garbage down from the Chrome Extensions website and quit wasting everyone's time?

It's so laughable at how he said months ago on Sep 19 and Sep 20 "I fixed it. It's fixed now" and the garbage is 100% as broken as it was the day before he "fixed it". For these geniuses that know so much more than I do about coding (I don't know anything), what have they truly accomplished except aggravate people and waste their time and put them through suffering. Because in the end, it's not how much you know. It's how you use your knowledge and your attitude in general towards people and life.
