### ISSUE TITLE
Messages for blocked contacts have messages deleted "for me" only, and are not "unsent"

### ISSUE THREAD

**Issue by jfnz** [theahura/shoot-the-messenger#110]
**Describe the bug**
The extension only deletes (does not unsend) messages to contacts who are blocked (either by you, or who have blocked you).

Tested with a blocked/unblocked contact. Blocked only deletes "for me" however unblocked deletes "for everyone".

Manually unsending the message to the blocked contact works as expected.

**To Reproduce**
1. Block a contact.
2. Run the extension.
3. Compare results with unblocked contact.
4. See error.

**Expected behavior**
Blocked contacts should have messages unsent in the same manner that unblocked contacts do.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 119.0.6045.209

**Logs**
N/A

**Comment by theahura** [comment]
Can you do me a favor and check to see if you can manually unsend images in cases where you are blocked by the other user? 

On my end, I cannot do that, which means this bug report really should be filed with facebook instead of here. 

For some additional context, the way this extension works is by pretending to be a person. It goes through and clicks all the menus that a person would click, and scrolls through messages the way a person would scroll through messages, and so on. It's just automated, so you can move faster and longer than a person would.

This means that there are some fundamental limitations -- anything that you as a person cannot do, this application cannot do. Facebook has made it so that if you are blocked, you cannot unsend a message. This tool is handicapped in the same way.
