### ISSUE TITLE
Suggestion: Start from the top to the bottom

### ISSUE THREAD

**Issue by jfilipeferreira96** [theahura/shoot-the-messenger#111]
I tested and the code works great. 
However it would be awesome to have a reverse mode where you start from the old messages to the new ones. Why? Because sometimes you just want to delete those old cringe messages without letting the other person know that you are deleting it.

**Comment by theahura** [comment]
I'd love to be able to support this because it would actually make a bunch of other things easier, but as far as I know there is no way to actually jump to the top of a message chain without loading in the whole thing by scrolling, and loading in the whole thing by scrolling will eventually crash chrome :cry: Do you by any chance know of some way to do this? It used to be possible with url hacking but no longer i think

> Because sometimes you just want to delete those old cringe messages without letting the other person know that you are deleting it.

Just a heads up that anyone who has an iphone will get a notification for every message this is unsent. This isn't unique to this tool -- its a combination of an operating system level decision made by apple and a notification decision made by meta, that impacts every unsend (including manual ones)

**Comment by jfilipeferreira96** [comment]
I managed to create a bash script that keeps scrolling but by any means it's a feasible solution for this project.

Thanks for the heads ups.
