### ISSUE TITLE
How not to delete the messages of other? I only want my messages to be unsent and not to delete the messages of other

### ISSUE THREAD

**Issue by realwayne** [theahura/shoot-the-messenger#26]

**Comment by theahura** [comment]
Unfortunately this isn't possible. I tried and tried and at one point had a working version that (ab)used the search in conversation feature to do it, but Facebook managed to change the API from under me so that version bricked. The issue is how chrome does memory management. 

I recommend backing up your data before using this app. I keep an eye out for implementing the extension this way, so if something changes I'll update the extension.
