### ISSUE TITLE
Messenger scrolling around like crazy after purge complete

### ISSUE THREAD

**Issue by JasonJShuler** [theahura/shoot-the-messenger#30]
Even after killing chrome and clicking stop, messenger was scrolling around - even in other conversations. Had to disable extension to get it to stop

**Comment by theahura** [comment]
the STOP button should fix that issue, I can look into that. 

The extension is designed to continue working after a refresh of the page, because the way it clears browser memory is by refreshing. Hacky, I know, but it was the only way I could see to avoid chrome crashing on super long messenger chains. Open to suggestions on how to avoid that, because I agree it's very user-unfriendly.

**Comment by theahura** [comment]
Can't replicate this issue, STOP works for me. Can you dump the chrome console logs and maybe your system specs?
