### ISSUE TITLE
can you please make it so that it doesn't remove the other person's messages

### ISSUE THREAD

**Issue by polagee321** [theahura/shoot-the-messenger#36]
Please sir I would highly appreciate if you would allow me to keep the messages of the other person instead of removing them along with mine, can you make such an option?

**Comment by polagee321** [comment]
I would highly appreciate any sort of response!

**Comment by theahura** [comment]
Unfortunately no. See: #33, #26, #15 for brief explanations of why this isn't possible. 

Very roughly, chrome memory management isn't good. Eventually, the application needs to refresh the page to wipe the memory and avoid chrome crashes. On refresh, you get sent back to the bottom. If you only remove one side of the messenger chain, you'll eventually reach a point on long messenger chains where you can't erase more because of the memory issue. 

Older versions solved this by using the search in conversation feature. Facebook break the ability to do that
