### ISSUE TITLE
Notifying iPhone users of unsend and not unsending older messages

### ISSUE THREAD

**Issue by kingofprivacy** [theahura/shoot-the-messenger#58]
I've been using this on messenger.com and while effective at removing recent messages, my friends who are iPhone users are receiving push notifications over and over that I have removed messages. It also only seems to remove recent messages, as Facebook doesn't have an 'Unsend for everyone' feature on my messenger for messages pre-2021.

**Comment by theahura** [comment]
The first thing is a known issue, see the notes at the bottom of the README: 
![image](https://user-images.githubusercontent.com/6380637/156725884-83a85fe1-61ba-4de2-8012-64c02d2d7c92.png)

The latter I think is incorrect, or at least I can't reproduce and can go as far back as I want to unsend whatever (just checked this right now to confirm). Can you send a screenshot of the latter?

**Comment by kingofprivacy** [comment]
Ah, gotcha - yeah I tested it out on a good friend to see how it worked and it did make me wary of doing this on older chats where I wouldn't want to be notifying people.

For me on messenger on some older messages, there is no "Unsend for Everyone" option and only a "Remove for you". As the extension is mimicking a real person, if there's no option for me to unsend an old message manually, then the tool won't be able to as well. I'm not sure if Facebook puts time limits on removal of messages in different countries perhaps.? 
 
Of course now I can't that to come up as soon as I want to screenshot it - I'll keep trying and keep you posted.

**Comment by UnmovableCheddar** [comment]
I have tested this right now: Unfriending an iPhone user and unsending a message DOES send a notification. So it looks like a note in README is no longer valid.

I have also tried moving a conversation to ignored - still sending notifications.

Blocking person in Messenger or on Facebook removes unsend option completely, so that's not an option.

It is possible that Facebook takes into account other things when deciding to send a notification or not. It could be similar to how they decide whether or not an incoming message falls into message requests or straight to inbox. And being friends is just one of several things that matters here.

If I were to guess, it's probably the duration of friendship, time passed since person was unfriended, number of messages exchanged, frequency of messages, other mutual activity outside of messenger, number of mutual friends and things like that. It's likely about some kind of a trust score, which, if high enough, would trigger a notification for anything, including unsent messages.

**Comment by theahura** [comment]
That's good to know, ill update the readme.

**Comment by barmonicin** [comment]
> Blocking person in Messenger or on Facebook removes unsend option completely, so that's not an option.

Sorry for necroing this issue. Have you tried this on Android? I have recently blocked a user and interestingly, I can still see the Remove For You feature. But I am not sure if the receiving end still gets notified if they are using an iPhone if I decided to remove the message. Unfortunately, I have no one to test with as we all use Android in our circle.

**Comment by barmonicin** [comment]
Sorry for necroing this but has any of you tried unsending old messages using iPhone's FB messenger to see if they can still receive these push notifications?

Someone posted on r/Facebookmessenger in Reddit 3 months ago:

> I'm not sure this is correct. I tested with 2 accounts I have and with some friends account. Only thing I noticed is that if the message was **sent recently (last month)**, then when you unsend it, **it will send a push notification to iPhone Messenger app**. If you **unsend old messages over 1 month,** then **no notification**s (but again who knows, this is just from 1 test). It is annoying Facebook doesn't make this policy clear. Also depends if the other user has Messenger installed. There is no notification if it the user is only on the desktop or in the Facebook mobile app.
> 
> I found this article that talks about this 10 minute window but I just did a test with a message that was sent 2 weeks ago and it sent a push notification to my Messenger app on iPhone.
> 
> https://www.mtlblog.com/facebook-will-finally-let-you-delete-private-messages-but-a-notification-stays
- Original post here: https://www.reddit.com/r/facebookmessenger/comments/k3x7of/comment/hmxwtd8/?utm_source=share&utm_medium=web2x&context=3 

I have no means to test because I am not an iPhone user so I wonder if any of you can kindly confirm?

**Comment by larryqiann** [comment]
This appears to be a technical limitation.

On iOS, it's not generally possible to run a background daemon that listens for events and updates data in the app. This would have the side effect of the iPhone app caching potentially deleted messages, and the app would have to synchronize on startup perhaps. This means that a user could potentially access deleted messages for longer than necessary.

However, when a push notification is delivered through APNS, the app is notified and provided a small window to run and do work in the background. The Messenger app is probably using this mechanism to perform the actual deletion of messages from the local device cache.

**Comment by harrystuart** [comment]
Any update on the diagnosis here?
