### ISSUE TITLE
Did something change recently, can't get it to work

### ISSUE THREAD

**Issue by DomGrieco** [theahura/shoot-the-messenger#87]
1. Downloaded most recent code base
2. unzipped
3. loaded unpacked into Chrome
4. Opened up messenger
5. selected a conversation
6. clicked the remove messages button
7. Nothing happens

I tried updating the manifest file to v3 but realized they aren't enforcing that right now and it was just a warning. Anyone else having issues? Did some div classes change?

**Comment by 8SecSleeper** [comment]
I'm seeing the version in the webstore is the old version still. Where it will get bot limited real quick and doesn't reverse scroll like it does on the github version. 

The store has version 5.5 which is the old version somehow, github has 5.4 which is the new version. 

Make sure your on messenger.com and reload the page after installing the unpacked extension. Otherwise the button won't work.

**Comment by 8SecSleeper** [comment]
Tested the chrome store version, it makes it about 20 messages and gets rate limited. The github version never gets rate limited and works as expected.

**Comment by theahura** [comment]
Interesting thanks for the flag. I'll take a look at why the deployment is wrong tonight

**Comment by DomGrieco** [comment]
> 

Thanks, I actually don't think I refreshed my messenger tab after I installed the github or store version. It's working as expected now.

**Comment by theahura** [comment]
I don't think anything is different in the chrome store version and github, but just in case i deployed a 5.6 version
