### ISSUE TITLE
Any chance of a Manifest V3 version of this?

### ISSUE THREAD

**Issue by badgerhome** [theahura/shoot-the-messenger#94]
Chrome no longer supports Manifest V2, any chance of a V3 of this? Thanks again for all your hard work.

**Comment by theahura** [comment]
i figured this day would come eventually, but ive been putting it off because I didn't want to deal with it. I'm also generally fairly busy, not sure when I'll I have time to mess with this

There's a converter here: https://developer.chrome.com/blog/extension-manifest-converter/ 
in case you want to try running the converter on the manifest yourself, i'd be happy to accept a PR for that

**Comment by theahura** [comment]
Updated!
