### ISSUE TITLE
Plugin Don't work 

### ISSUE THREAD

**Issue by jbartak** [theahura/shoot-the-messenger#98]
**Describe the bug**
```
main.js:83 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'scrollTop' in null
    at getScroller (main.js:83:24)
    at prepareDOMForRemoval (main.js:133:3)
    at unsendAllVisibleMessages (main.js:162:36)
    at runner (main.js:285:29)
    at removeHandler (main.js:393:24)
```

**To Reproduce**
1. Go to messenger.com and open specific chat
2. Click on Remove messages

**Expected behavior**
Plugin works.

**Screenshots**
![image](https://github.com/theahura/shoot-the-messenger/assets/9643757/d41a3f7f-c1a2-4286-8826-3db3accf6b9a)

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Chrome
 - Version 115.0.5790.110

**Logs**
N/A

**Comment by theahura** [comment]
This happens when the extension can't find a scroll bar in the messenger chain. That in turn can happen for a few reasons
- the messenger chain isn't long enough
- Facebook changed their UI so that the query we use to find the scroll bar no longer works

To fix the former, test on a longer messenger chain. I recommend just messaging yourself to see if it works

To fix the latter, we'll need to update the code. As a test, try the following code in the chrome dev console:
```
MY_ROW_QUERY = '.x78zum5.xdt5ytf.x193iq5w.x1n2onr6.xuk3077:has(> span)'; // Also used for finding the scroller (we just go up to the first parent w/ scrollTop)
PARTNER_CHAT_QUERY = '.x6prxxf.x1fc57z9.x1yc453h.x126k92a.xzsf02u'; // Partner chat text innerText, used for searching
UNSENT_MESSAGE_QUERY = '[aria-label="You unsent a message"]'; // In case a user has none of their own messages on screen and only unsent messages, this serves to pick up the scroll parent.

const query = `${MY_ROW_QUERY}, ${PARTNER_CHAT_QUERY}, ${UNSENT_MESSAGE_QUERY}`;
let el = document.querySelectorAll(query);

console.log(el)
```

This code just checks to see if the queries for the messenge row works as intended. 

If you get a chance to try either result, update the thread with what you find
